/* {{{ The MIT License (MIT)

Copyright (c) 2001, 2013 Johan Kotlinski

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. }}} */

/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 63

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TileLabelBank 0

/* Gameboy Color palette 0 */
#define TileLabelCGBPal0c0 6142
#define TileLabelCGBPal0c1 8935
#define TileLabelCGBPal0c2 1351
#define TileLabelCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TileLabelCGBPal1c0 6076
#define TileLabelCGBPal1c1 8935
#define TileLabelCGBPal1c2 6596
#define TileLabelCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TileLabelCGBPal2c0 6076
#define TileLabelCGBPal2c1 8935
#define TileLabelCGBPal2c2 6596
#define TileLabelCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TileLabelCGBPal3c0 6076
#define TileLabelCGBPal3c1 8935
#define TileLabelCGBPal3c2 6596
#define TileLabelCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TileLabelCGBPal4c0 6076
#define TileLabelCGBPal4c1 8935
#define TileLabelCGBPal4c2 6596
#define TileLabelCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TileLabelCGBPal5c0 6076
#define TileLabelCGBPal5c1 8935
#define TileLabelCGBPal5c2 6596
#define TileLabelCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TileLabelCGBPal6c0 6076
#define TileLabelCGBPal6c1 8935
#define TileLabelCGBPal6c2 6596
#define TileLabelCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TileLabelCGBPal7c0 6076
#define TileLabelCGBPal7c1 8935
#define TileLabelCGBPal7c2 6596
#define TileLabelCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char TileLabelCGB[];
/* Start of tile array. */
extern unsigned char TileLabel[];

/* End of EXPORT.H */
